def pic_params(pic, con=.9, reg=None):
    return {'pic': pic, 'con': con, 'reg': reg}


class Pics:
    home_active_btn = pic_params('home_active_btn')
    home_inactive_btn = pic_params('home_inactive_btn')
    transfers_active_btn = pic_params('transfers_active_btn')
    transfers_inactive_btn = pic_params('transfers_inactive_btn')
    enter_pwd_field = pic_params('enter_pwd_field')
    homescreen = pic_params('homescreen')
    homescreen2 = pic_params('homescreen2')
    login_btn = pic_params('login_btn')
    sign_in_btn = pic_params('sign_in_btn')
    software_update = pic_params('software_update')
    software_update_ok = pic_params('software_update_ok')
    software_update_update = pic_params('software_update_update')
    software_update_cancel = pic_params('software_update_cancel')
    software_update_confirm_btn = pic_params('software_update_confirm_btn')
    home_menu_checkpoint = pic_params('home_menu_checkpoint')
    transfers_menu_checkpoint = pic_params('transfers_menu_checkpoint')
    transfers_list_checkpoint = pic_params('transfers_list_checkpoint')
    transfers_market_checkpoint = pic_params('transfers_market_checkpoint')
    transfers_list_btn = pic_params('transfers_list_btn')
    transfers_market_btn = pic_params('transfers_market_btn')

    clear_sold_players_btn = pic_params('clear_sold_players_btn')
    re_list_players_btn = pic_params('re_list_players_btn')

    confirm = pic_params('confirm')
    cannot_authenticate = pic_params('cannot_authenticate')

    bid_price_increment_btn = pic_params(r'increment_btn', reg=())
    bid_price_decrement_btn = pic_params(r'decrement_btn', reg=())

    sell_price_min_increment_btn = pic_params(r'increment_btn', reg=())
    sell_price_min_decrement_btn = pic_params(r'decrement_btn', reg=())

    sell_price_max_increment_btn = pic_params(r'increment_btn', reg=())
    sell_price_max_decrement_btn = pic_params(r'decrement_btn', reg=())

    search_btn = pic_params(r'search_btn')
    reset_player_name_btn = pic_params(r'reset_player_name_btn')
    reset_filter_btn = pic_params(r'reset_filter_btn')
    reset_bid_price_btn = pic_params(r'reset_bid_price_btn')
    reset_buy_price_btn = pic_params(r'reset_buy_price_btn')
    type_player_name = pic_params(r'type_player_name')
    player_name_not_found = pic_params(r'player_name_not_found')
    quality_menu_btn = pic_params(r'quality_menu_btn')
    rarity_menu_btn = pic_params(r'rarity_menu_btn')
    max_buy_price_btn = pic_params(r'max_buy_price_btn')
    enter_price_checkpoint = pic_params(r'enter_price_checkpoint')
    no_results = pic_params(r'no_results')
    result = pic_params(r'result')
    quality_bronze = pic_params(r'quality_bronze')
    quality_silver = pic_params(r'quality_silver')
    quality_gold = pic_params(r'quality_gold')
    quality_special = pic_params(r'quality_special')
    rarity_common = pic_params(r'rarity_common')
    rarity_rare = pic_params(r'rarity_rare')
    rarity_totw = pic_params(r'rarity_totw')
